#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MaterialDesignHelpers.Resource", IsApplication=false)]

namespace MaterialDesignHelpers
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0200b7
			public static int material_amber_100 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public static int material_amber_200 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public static int material_amber_300 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public static int material_amber_400 = 2130837690;
			
			// aapt resource value: 0x7f0200b6
			public static int material_amber_50 = 2130837686;
			
			// aapt resource value: 0x7f0200bb
			public static int material_amber_500 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public static int material_amber_600 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public static int material_amber_700 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public static int material_amber_800 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public static int material_amber_900 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public static int material_amber_accent_100 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public static int material_amber_accent_200 = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public static int material_amber_accent_400 = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public static int material_amber_accent_700 = 2130837699;
			
			// aapt resource value: 0x7f020047
			public static int material_blue_100 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public static int material_blue_200 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public static int material_blue_300 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public static int material_blue_400 = 2130837578;
			
			// aapt resource value: 0x7f020046
			public static int material_blue_50 = 2130837574;
			
			// aapt resource value: 0x7f02004b
			public static int material_blue_500 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public static int material_blue_600 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public static int material_blue_700 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public static int material_blue_800 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public static int material_blue_900 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public static int material_blue_accent_100 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public static int material_blue_accent_200 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public static int material_blue_accent_400 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public static int material_blue_accent_700 = 2130837587;
			
			// aapt resource value: 0x7f0200f5
			public static int material_blue_grey_100 = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public static int material_blue_grey_200 = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public static int material_blue_grey_300 = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public static int material_blue_grey_400 = 2130837752;
			
			// aapt resource value: 0x7f0200f4
			public static int material_blue_grey_50 = 2130837748;
			
			// aapt resource value: 0x7f0200f9
			public static int material_blue_grey_500 = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public static int material_blue_grey_600 = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public static int material_blue_grey_700 = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public static int material_blue_grey_800 = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public static int material_blue_grey_900 = 2130837757;
			
			// aapt resource value: 0x7f0200e1
			public static int material_brown_100 = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public static int material_brown_200 = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public static int material_brown_300 = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public static int material_brown_400 = 2130837732;
			
			// aapt resource value: 0x7f0200e0
			public static int material_brown_50 = 2130837728;
			
			// aapt resource value: 0x7f0200e5
			public static int material_brown_500 = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public static int material_brown_600 = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public static int material_brown_700 = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public static int material_brown_800 = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public static int material_brown_900 = 2130837737;
			
			// aapt resource value: 0x7f020063
			public static int material_cyan_100 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public static int material_cyan_200 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public static int material_cyan_300 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public static int material_cyan_400 = 2130837606;
			
			// aapt resource value: 0x7f020062
			public static int material_cyan_50 = 2130837602;
			
			// aapt resource value: 0x7f020067
			public static int material_cyan_500 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public static int material_cyan_600 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public static int material_cyan_700 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public static int material_cyan_800 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public static int material_cyan_900 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public static int material_cyan_accent_100 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public static int material_cyan_accent_200 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public static int material_cyan_accent_400 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public static int material_cyan_accent_700 = 2130837615;
			
			// aapt resource value: 0x7f0200d3
			public static int material_deep_orange_100 = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public static int material_deep_orange_200 = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public static int material_deep_orange_300 = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public static int material_deep_orange_400 = 2130837718;
			
			// aapt resource value: 0x7f0200d2
			public static int material_deep_orange_50 = 2130837714;
			
			// aapt resource value: 0x7f0200d7
			public static int material_deep_orange_500 = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public static int material_deep_orange_600 = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public static int material_deep_orange_700 = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public static int material_deep_orange_800 = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public static int material_deep_orange_900 = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public static int material_deep_orange_accent_100 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public static int material_deep_orange_accent_200 = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public static int material_deep_orange_accent_400 = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public static int material_deep_orange_accent_700 = 2130837727;
			
			// aapt resource value: 0x7f02002b
			public static int material_deep_purple_100 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int material_deep_purple_200 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int material_deep_purple_300 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int material_deep_purple_400 = 2130837550;
			
			// aapt resource value: 0x7f02002a
			public static int material_deep_purple_50 = 2130837546;
			
			// aapt resource value: 0x7f02002f
			public static int material_deep_purple_500 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public static int material_deep_purple_600 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public static int material_deep_purple_700 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public static int material_deep_purple_800 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int material_deep_purple_900 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int material_deep_purple_accent_100 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public static int material_deep_purple_accent_200 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public static int material_deep_purple_accent_400 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public static int material_deep_purple_accent_700 = 2130837559;
			
			// aapt resource value: 0x7f02007f
			public static int material_green_100 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public static int material_green_200 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public static int material_green_300 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public static int material_green_400 = 2130837634;
			
			// aapt resource value: 0x7f02007e
			public static int material_green_50 = 2130837630;
			
			// aapt resource value: 0x7f020083
			public static int material_green_500 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public static int material_green_600 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public static int material_green_700 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public static int material_green_800 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public static int material_green_900 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public static int material_green_accent_100 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public static int material_green_accent_200 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public static int material_green_accent_400 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public static int material_green_accent_700 = 2130837643;
			
			// aapt resource value: 0x7f0200eb
			public static int material_grey_100 = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public static int material_grey_200 = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public static int material_grey_300 = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public static int material_grey_400 = 2130837742;
			
			// aapt resource value: 0x7f0200ea
			public static int material_grey_50 = 2130837738;
			
			// aapt resource value: 0x7f0200ef
			public static int material_grey_500 = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public static int material_grey_600 = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public static int material_grey_700 = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public static int material_grey_800 = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public static int material_grey_900 = 2130837747;
			
			// aapt resource value: 0x7f020039
			public static int material_indigo_100 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public static int material_indigo_200 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public static int material_indigo_300 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public static int material_indigo_400 = 2130837564;
			
			// aapt resource value: 0x7f020038
			public static int material_indigo_50 = 2130837560;
			
			// aapt resource value: 0x7f02003d
			public static int material_indigo_500 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public static int material_indigo_600 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public static int material_indigo_700 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public static int material_indigo_800 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public static int material_indigo_900 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public static int material_indigo_accent_100 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public static int material_indigo_accent_200 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public static int material_indigo_accent_400 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public static int material_indigo_accent_700 = 2130837573;
			
			// aapt resource value: 0x7f0200fe
			public static int material_light_black = 2130837758;
			
			// aapt resource value: 0x7f020055
			public static int material_light_blue_100 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public static int material_light_blue_200 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public static int material_light_blue_300 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public static int material_light_blue_400 = 2130837592;
			
			// aapt resource value: 0x7f020054
			public static int material_light_blue_50 = 2130837588;
			
			// aapt resource value: 0x7f020059
			public static int material_light_blue_500 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public static int material_light_blue_600 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public static int material_light_blue_700 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public static int material_light_blue_800 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public static int material_light_blue_900 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public static int material_light_blue_accent_100 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public static int material_light_blue_accent_200 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public static int material_light_blue_accent_400 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public static int material_light_blue_accent_700 = 2130837601;
			
			// aapt resource value: 0x7f02008d
			public static int material_light_green_100 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public static int material_light_green_200 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public static int material_light_green_300 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public static int material_light_green_400 = 2130837648;
			
			// aapt resource value: 0x7f02008c
			public static int material_light_green_50 = 2130837644;
			
			// aapt resource value: 0x7f020091
			public static int material_light_green_500 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public static int material_light_green_600 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public static int material_light_green_700 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public static int material_light_green_800 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public static int material_light_green_900 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public static int material_light_green_accent_100 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public static int material_light_green_accent_200 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public static int material_light_green_accent_400 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public static int material_light_green_accent_700 = 2130837657;
			
			// aapt resource value: 0x7f0200ff
			public static int material_light_white = 2130837759;
			
			// aapt resource value: 0x7f02009b
			public static int material_lime_100 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public static int material_lime_200 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public static int material_lime_300 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public static int material_lime_400 = 2130837662;
			
			// aapt resource value: 0x7f02009a
			public static int material_lime_50 = 2130837658;
			
			// aapt resource value: 0x7f02009f
			public static int material_lime_500 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public static int material_lime_600 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public static int material_lime_700 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public static int material_lime_800 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public static int material_lime_900 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public static int material_lime_accent_100 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public static int material_lime_accent_200 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public static int material_lime_accent_400 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public static int material_lime_accent_700 = 2130837671;
			
			// aapt resource value: 0x7f0200c5
			public static int material_orange_100 = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public static int material_orange_200 = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public static int material_orange_300 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public static int material_orange_400 = 2130837704;
			
			// aapt resource value: 0x7f0200c4
			public static int material_orange_50 = 2130837700;
			
			// aapt resource value: 0x7f0200c9
			public static int material_orange_500 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public static int material_orange_600 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public static int material_orange_700 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public static int material_orange_800 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public static int material_orange_900 = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public static int material_orange_accent_100 = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public static int material_orange_accent_200 = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public static int material_orange_accent_400 = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public static int material_orange_accent_700 = 2130837713;
			
			// aapt resource value: 0x7f02000f
			public static int material_pink_100 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int material_pink_200 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int material_pink_300 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int material_pink_400 = 2130837522;
			
			// aapt resource value: 0x7f02000e
			public static int material_pink_50 = 2130837518;
			
			// aapt resource value: 0x7f020013
			public static int material_pink_500 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int material_pink_600 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int material_pink_700 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int material_pink_800 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int material_pink_900 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int material_pink_accent_100 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int material_pink_accent_200 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int material_pink_accent_400 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int material_pink_accent_700 = 2130837531;
			
			// aapt resource value: 0x7f02001d
			public static int material_purple_100 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int material_purple_200 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int material_purple_300 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int material_purple_400 = 2130837536;
			
			// aapt resource value: 0x7f02001c
			public static int material_purple_50 = 2130837532;
			
			// aapt resource value: 0x7f020021
			public static int material_purple_500 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int material_purple_600 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int material_purple_700 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int material_purple_800 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int material_purple_900 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int material_purple_accent_100 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int material_purple_accent_200 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int material_purple_accent_400 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int material_purple_accent_700 = 2130837545;
			
			// aapt resource value: 0x7f020001
			public static int material_red_100 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int material_red_200 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int material_red_300 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int material_red_400 = 2130837508;
			
			// aapt resource value: 0x7f020000
			public static int material_red_50 = 2130837504;
			
			// aapt resource value: 0x7f020005
			public static int material_red_500 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int material_red_600 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int material_red_700 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int material_red_800 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int material_red_900 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int material_red_accent_100 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int material_red_accent_200 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int material_red_accent_400 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int material_red_accent_700 = 2130837517;
			
			// aapt resource value: 0x7f020071
			public static int material_teal_100 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public static int material_teal_200 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public static int material_teal_300 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public static int material_teal_400 = 2130837620;
			
			// aapt resource value: 0x7f020070
			public static int material_teal_50 = 2130837616;
			
			// aapt resource value: 0x7f020075
			public static int material_teal_500 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public static int material_teal_600 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public static int material_teal_700 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public static int material_teal_800 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public static int material_teal_900 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public static int material_teal_accent_100 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public static int material_teal_accent_200 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public static int material_teal_accent_400 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public static int material_teal_accent_700 = 2130837629;
			
			// aapt resource value: 0x7f0200a9
			public static int material_yellow_100 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public static int material_yellow_200 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public static int material_yellow_300 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public static int material_yellow_400 = 2130837676;
			
			// aapt resource value: 0x7f0200a8
			public static int material_yellow_50 = 2130837672;
			
			// aapt resource value: 0x7f0200ad
			public static int material_yellow_500 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public static int material_yellow_600 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public static int material_yellow_700 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public static int material_yellow_800 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public static int material_yellow_900 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public static int material_yellow_accent_100 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public static int material_yellow_accent_200 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public static int material_yellow_accent_400 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public static int material_yellow_accent_700 = 2130837685;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030013
			public static int material_component_bottom_sheet_edge_left_right_margins = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int material_component_bottom_sheet_edge_top_bottom_margins = 2130903060;
			
			// aapt resource value: 0x7f030015
			public static int material_component_bottom_sheet_list_item_height = 2130903061;
			
			// aapt resource value: 0x7f030016
			public static int material_component_bottom_sheet_list_item_text_horizontal_padding = 2130903062;
			
			// aapt resource value: 0x7f03001b
			public static int material_component_button_corner_radius = 2130903067;
			
			// aapt resource value: 0x7f030018
			public static int material_component_button_dense_height = 2130903064;
			
			// aapt resource value: 0x7f03001e
			public static int material_component_button_dense_text_size = 2130903070;
			
			// aapt resource value: 0x7f030017
			public static int material_component_button_height = 2130903063;
			
			// aapt resource value: 0x7f030019
			public static int material_component_button_min_width = 2130903065;
			
			// aapt resource value: 0x7f03001c
			public static int material_component_button_text_left_and_right_padding = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public static int material_component_button_text_size = 2130903069;
			
			// aapt resource value: 0x7f03001a
			public static int material_component_button_touchable_target_height = 2130903066;
			
			// aapt resource value: 0x7f030024
			public static int material_component_cards_action_button_row_padding = 2130903076;
			
			// aapt resource value: 0x7f030027
			public static int material_component_cards_left_and_right_padding = 2130903079;
			
			// aapt resource value: 0x7f030029
			public static int material_component_cards_padding_from_edge_of_screen_to_card = 2130903081;
			
			// aapt resource value: 0x7f030023
			public static int material_component_cards_primary_title_bottom_padding = 2130903075;
			
			// aapt resource value: 0x7f030022
			public static int material_component_cards_primary_title_top_padding = 2130903074;
			
			// aapt resource value: 0x7f03002a
			public static int material_component_cards_space_between_cards = 2130903082;
			
			// aapt resource value: 0x7f030026
			public static int material_component_cards_supporting_text_bottom_padding = 2130903078;
			
			// aapt resource value: 0x7f030025
			public static int material_component_cards_supporting_text_top_padding = 2130903077;
			
			// aapt resource value: 0x7f030028
			public static int material_component_cards_top_and_bottom_padding = 2130903080;
			
			// aapt resource value: 0x7f03002e
			public static int material_component_dialogs_action_area_height = 2130903086;
			
			// aapt resource value: 0x7f030030
			public static int material_component_dialogs_elevation = 2130903088;
			
			// aapt resource value: 0x7f03002d
			public static int material_component_dialogs_padding_around_buttons = 2130903085;
			
			// aapt resource value: 0x7f03002b
			public static int material_component_dialogs_padding_around_content_area = 2130903083;
			
			// aapt resource value: 0x7f030031
			public static int material_component_dialogs_padding_below_touch_target_to_dialog_edge = 2130903089;
			
			// aapt resource value: 0x7f030032
			public static int material_component_dialogs_padding_between_button_text_right_edge_and_dialog_edge = 2130903090;
			
			// aapt resource value: 0x7f03002f
			public static int material_component_dialogs_padding_between_text_and_touch_target = 2130903087;
			
			// aapt resource value: 0x7f03002c
			public static int material_component_dialogs_padding_between_title_and_body_text = 2130903084;
			
			// aapt resource value: 0x7f03001f
			public static int material_component_floating_action_button_margin = 2130903071;
			
			// aapt resource value: 0x7f030021
			public static int material_component_floating_action_button_mini_size = 2130903073;
			
			// aapt resource value: 0x7f030020
			public static int material_component_floating_action_button_size = 2130903072;
			
			// aapt resource value: 0x7f030033
			public static int material_component_grid_lists_header_footer_height = 2130903091;
			
			// aapt resource value: 0x7f030034
			public static int material_component_grid_lists_header_footer_text_padding = 2130903092;
			
			// aapt resource value: 0x7f030035
			public static int material_component_grid_lists_header_footer_text_size = 2130903093;
			
			// aapt resource value: 0x7f030037
			public static int material_component_grid_lists_padding_big = 2130903095;
			
			// aapt resource value: 0x7f030038
			public static int material_component_grid_lists_padding_small = 2130903096;
			
			// aapt resource value: 0x7f030036
			public static int material_component_grid_lists_two_line_header_footer_height = 2130903094;
			
			// aapt resource value: 0x7f030039
			public static int material_component_lists_icon_left_padding = 2130903097;
			
			// aapt resource value: 0x7f03003d
			public static int material_component_lists_padding_above_list = 2130903101;
			
			// aapt resource value: 0x7f03003b
			public static int material_component_lists_right_padding = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public static int material_component_lists_single_line_height = 2130903100;
			
			// aapt resource value: 0x7f03003f
			public static int material_component_lists_single_line_text_size = 2130903103;
			
			// aapt resource value: 0x7f03003e
			public static int material_component_lists_single_line_with_avatar_height = 2130903102;
			
			// aapt resource value: 0x7f03003a
			public static int material_component_lists_text_left_padding = 2130903098;
			
			// aapt resource value: 0x7f030044
			public static int material_component_lists_text_padding_bottom = 2130903108;
			
			// aapt resource value: 0x7f030043
			public static int material_component_lists_three_line_height = 2130903107;
			
			// aapt resource value: 0x7f030040
			public static int material_component_lists_two_line_height = 2130903104;
			
			// aapt resource value: 0x7f030042
			public static int material_component_lists_two_line_secondary_text_size = 2130903106;
			
			// aapt resource value: 0x7f030041
			public static int material_component_lists_two_line_text_size = 2130903105;
			
			// aapt resource value: 0x7f030045
			public static int material_component_text_fields_floating_label_height = 2130903109;
			
			// aapt resource value: 0x7f030046
			public static int material_component_text_fields_floating_label_padding_above_label_text = 2130903110;
			
			// aapt resource value: 0x7f030048
			public static int material_component_text_fields_floating_label_padding_below_input_text_including_divider = 2130903112;
			
			// aapt resource value: 0x7f030049
			public static int material_component_text_fields_floating_label_padding_below_text_divider = 2130903113;
			
			// aapt resource value: 0x7f030047
			public static int material_component_text_fields_floating_label_padding_between_label_and_input_text = 2130903111;
			
			// aapt resource value: 0x7f03004a
			public static int material_component_text_fields_icon_height = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public static int material_component_text_fields_padding_above_and_below_label = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public static int material_component_text_full_width_single_line_text_field_height = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public static int material_component_text_full_width_single_line_text_field_text_top_and_bottom_padding = 2130903117;
			
			// aapt resource value: 0x7f03000e
			public static int material_layout_app_bar_height = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int material_layout_app_bar_horizontal_padding = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int material_layout_app_bar_icon_padding = 2130903056;
			
			// aapt resource value: 0x7f030012
			public static int material_layout_app_bar_title_bottom_padding = 2130903058;
			
			// aapt resource value: 0x7f030011
			public static int material_layout_app_bar_title_left_padding = 2130903057;
			
			// aapt resource value: 0x7f03000a
			public static int material_layout_avatar = 2130903050;
			
			// aapt resource value: 0x7f03000d
			public static int material_layout_button_height = 2130903053;
			
			// aapt resource value: 0x7f03000b
			public static int material_layout_icon = 2130903051;
			
			// aapt resource value: 0x7f030001
			public static int material_layout_keylines_content_left_margin_from_screen_edge = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int material_layout_keylines_horizontal_mobile_margin = 2130903042;
			
			// aapt resource value: 0x7f030000
			public static int material_layout_keylines_screen_edge_margin = 2130903040;
			
			// aapt resource value: 0x7f03000c
			public static int material_layout_touch_target = 2130903052;
			
			// aapt resource value: 0x7f030007
			public static int material_layout_vertical_spacing_between_content_areas = 2130903047;
			
			// aapt resource value: 0x7f030006
			public static int material_layout_vertical_spacing_list_item = 2130903046;
			
			// aapt resource value: 0x7f030009
			public static int material_layout_vertical_spacing_navigation_right_margin = 2130903049;
			
			// aapt resource value: 0x7f030008
			public static int material_layout_vertical_spacing_right_side_icons_margin = 2130903048;
			
			// aapt resource value: 0x7f030003
			public static int material_layout_vertical_spacing_status_bar = 2130903043;
			
			// aapt resource value: 0x7f030005
			public static int material_layout_vertical_spacing_subtitle = 2130903045;
			
			// aapt resource value: 0x7f030004
			public static int material_layout_vertical_spacing_tool_bar = 2130903044;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
	}
}
#pragma warning restore 1591
